let cat = {
  adults: "adults",
  documental: "docuemntal",
  nwes: "news",
  movie: "movie",
  music: "music",
  sports: "sports",
};

export const datos = [
  {
    id: 1,
    name: "Canal 2 (Perico)",
    img: "http://canal2perico.com.ar/canal2/images/logo.png",
    link1: "https://streamcasthd.com:2020/VideoPlayer/tecnovisioncanal2tv",
    link2: "",
    link3: "",
    link4: "",
    category: cat.nwes,
  },
  {
    id: 2,
    name: "Canal 2 Jujuy",
    img: "http://canal2jujuy.com/canal2/wp-content/uploads/2020/02/logoc2fw.png",
    link1:
      "https://livestream.com/accounts/679322/events/3782013/player?width=640&height=360&autoPlay=true&mute=false",
    link2: "",
    link3: "",
    link4: "",
    category: cat.nwes,
  },
  {
    id: 3,
    name: "Canal 4 Jujuy",
    img: "https://i0.wp.com/directostv.teleame.com/wp-content/uploads/2016/05/Canal-4-Jujuy-en-vivo-Online.png?resize=1068%2C601&ssl=1",
    link1: "https://canal4jujuy.elcuatro.com/",
    link2: "",
    link3: "",
    link4: "",
    category: cat.nwes,
  },
  {
    id: 4,
    name: "Canal 7 Jujuy",
    img: "https://static.wikia.nocookie.net/logopedia/images/4/4c/Canal_Siete_Jujuy_%28Logo_2020_-_2%29.png/",
    link1: "https://arcast.com.ar/canal7jujuy/",
    link2: "https://canal7dejujuy.com.ar/",
    link3: "",
    link4: "",
    category: cat.news,
  },
  {
    id: 5,
    name: "Telefe",
    img: "https://static.wikia.nocookie.net/logopedia/images/0/01/Telefe_2018_3D.svg/",
    link1: "https://test01.cloud.telefe.com/vivo/",
    link2: "",
    link3: "https://blackface.world/dtvpl.html?id=1216",
    link4: "https://embed8.alandesk.life/cvatt.html?get=VGVsZWZlSEQ=&lang=1",
    category: cat.nwes,
  },
  {
    id: 6,
    name: "TN",
    img: "https://static.wikia.nocookie.net/logopedia/images/4/4f/TN_todo_noticias_logo.svg/",
    link1: "https://www.youtube.com/embed/HPiv1pzIPRc",
    link2: "",
    link3: "https://embed8.alandesk.life/cvatt.html?get=VG9kb05vdGljaWFz",
    link4: "https://blackface.world/dtvpl.html?id=1225", //"https://www.latele-envivo.com/Embed/tn/op2.php",
    category: cat.nwes,
  },
  {
    id: 7,
    name: "El Trece",
    img: "https://i0.wp.com/directostv.teleame.com/wp-content/uploads/2019/10/El-Trece-en-vivo-Online.png?resize=1068%2C601&ssl=1",
    link1: "https://www.eltrecetv.com.ar/vivo/",
    link2: "",
    link3: "https://blackface.world/dtvpl.html?id=1095",
    link4: "https://embed8.alandesk.life/cvatt.html?get=QXJ0ZWFySEQ",
    category: cat.nwes,
  },
  {
    id: 8,
    name: "LN+",
    img: "https://static.wikia.nocookie.net/logopedia/images/0/0e/LN_Mas.svg/",
    link1: "https://www.youtube.com/embed/4e8Iw3Frf1A",
    link2: "https://lnmas.lanacion.com.ar/",
    link3: "https://blackface.world/dtvpl.html?id=1154",
    link4: "https://embed8.alandesk.life/cvatt.html?get=TGFfTmFjaW9u",
    category: cat.nwes,
  },
  {
    id: 9,
    name: "América",
    img: "https://i1.wp.com/static.americadigital.com.ar/americatv/images/america-tv-junio.png",
    link1: "https://www.americatv.com.ar/vivo",
    link2: "",
    link3: "https://blackface.world/dtvpl.html?id=1010",
    link4: "https://embed8.alandesk.life/cvatt.html?get=QW1lcmljYVRW",
    category: cat.nwes,
  },
  {
    id: 10,
    name: "A24",
    img: "https://www.a24.com/assets/img/296/header-logo.svg",
    link1: "https://www.youtube.com/embed/QGpHLgRnrx4",
    link2: "https://www.a24.com/vivo",
    link3: "https://blackface.world/dtvpl.html?id=1009",
    link4: "https://embed8.alandesk.life/cvatt.html?get=QW1lcmljYTI0",
    category: cat.nwes,
  },
  {
    id: 11,
    name: "Canal 26",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Canal_26_logo_%282022%29.svg/441px-Canal_26_logo_%282022%29.svg.png",
    link1: "https://www.youtube.com/embed/XcoIpif-pcM",
    link2: "https://www.canal26.com/canal26-en-vivo",
    link3: "https://blackface.world/dtvpl.html?id=1031",
    link4: "https://embed8.alandesk.life/cvatt.html?get=MjZfVFZfSEQ",
    category: cat.nwes,
  },
  {
    id: 12,
    name: "El Nueve ",
    img: "https://www.elnueve.com.ar/_next/image?url=%2Flogo%2FlogotipoC9.png&w=640&q=75",
    link1: "https://www.elnueve.com.ar/en-vivo",
    link2: "",
    link3: "https://blackface.world/dtvpl.html?id=1032",
    link4: "https://embed8.alandesk.life/cvatt.html?get=Q2FuYWw5",
    category: cat.nwes,
  },
  {
    id: 13,
    name: "C5N",
    img: "https://www.c5n.com/css-custom/326/images/logo-c5n.svg",
    link1: "https://www.youtube.com/embed/wBWK9tV9hBM",
    link2: "https://www.c5n.com/vivo",
    link3: "https://blackface.world/dtvpl.html?id=1028",
    link4: "https://embed8.alandesk.life/cvatt.html?get=QzVO",
    category: cat.nwes,
  }, ///////////////////////////////////////////////////////////////////
  {
    id: 14,
    name: "TV Pública",
    img: "https://www.tvpublica.com.ar/static/img/branding/isologo.svg",
    link1: "https://blackface.world/dtvpl.html?id=1156",
    link2: "https://embed8.alandesk.life/cvatt.html?get=Q2FuYWw3",
    link3: "",
    link4: "",
    category: cat.nwes,
  },
  {
    id: 15,
    name: "Crónica",
    img: "https://static.wikia.nocookie.net/logopedia/images/c/cd/Cr%C3%B3nica_TV_2018.svg/",
    link1: "https://embed8.alandesk.life/cvatt.html?get=Q3JvbmljYVRW",
    link2: "https://www.youtube.com/embed/InSydaLSSlw?autoplay=true",
    link3: "",
    link4: "",
    category: cat.nwes,
  },
  {
    id: 16,
    name: "STAR+",
    img: "https://logospng.org/download/star-plus/logo-star-plus-256.png",
    link1: "https://canales.online/star-plus/",
    link2: "https://librefutboltv.com/star-plus/",
    link3: "",
    link4: "",
    category: cat.sports,
  },
  {
    id: 17,
    name: "ESPN",
    img: "https://static.wikia.nocookie.net/logopedia/images/3/34/ESPN.svg/",
    link1: "https://blackface.world/dtvpl.html?id=1104",
    link2: "https://embed8.alandesk.life/cvatt.html?get=RVNQTjJIRA&lang=1",
    link3: "",
    link4: "",
    category: cat.sports,
  },
  {
    id: 18,
    name: "ESPN2",
    img: "https://static.wikia.nocookie.net/logopedia/images/d/d5/ESPN2.svg/",
    link1: "https://blackface.world/dtvpl.html?id=1099",
    link2: "https://embed8.alandesk.life/cvatt.html?get=RVNQTjJfQXJn",
    link3: "",
    link4: "",
    category: cat.sports,
  },
  {
    id: 19,
    name: "ESPN3",
    img: "https://static.wikia.nocookie.net/logopedia/images/d/d2/ESPN_3.svg/",
    link1: "https://blackface.world/dtvpl.html?id=1103",
    link2: "https://embed8.alandesk.life/cvatt.html?get=RVNQTjM",
    link3: "",
    link4: "",
    category: cat.sports,
  },
  {
    id: 20,
    name: "ESPN EXTRA",
    img: "https://static.wikia.nocookie.net/logopedia/images/b/b5/ESPN_Extra_Brazil_logo.png/",
    link1: "https://blackface.world/dtvpl.html?id=1107",
    link2: "https://embed8.alandesk.life/cvatt.html?get=RVNQTkhE",
    link3: "",
    link4: "",
    category: cat.sports,
  },
  {
    id: 21,
    name: "ESPN PREMIUM",
    img: "https://static.wikia.nocookie.net/logopedia/images/5/5b/ESPN_Premium_%282022%29.svg/",
    link1: "https://blackface.world/dtvpl.html?id=1125&lang=1",
    link2:
      "https://embed8.alandesk.life/cvatt.html?get=Rm94X1Nwb3J0c19QcmVtaXVuX0hE&lang=1",
    link3: "",
    link4: "",
    category: cat.sports,
  },
  {
    id: 22,
    name: "TNT SPORTS",
    img: "https://static.wikia.nocookie.net/logopedia/images/9/9c/TNT_Sports.svg/",
    link1: "",
    link2: "",
    link3: "",
    link4: "",
    category: cat,
  },
  {
    id: 23,
    name: "TyC Sports",
    img: "https://static.wikia.nocookie.net/logopedia/images/5/5d/TyC_Sports.svg/",
    link1: "https://blackface.world/dtvpl.html?id=1240",
    link2: "https://embed8.alandesk.life/cvatt.html?get=VHlDU3BvcnQ",
    link3: "",
    link4: "",
    category: cat.sports,
  },
  {
    id: 24,
    name: "FOX SPORTS",
    img: "https://static.wikia.nocookie.net/logopedia/images/b/b2/Fox_Sports_Argentina_2023.svg/",
    link1: "https://blackface.world/dtvpl.html?id=1118",
    link2: "https://embed8.alandesk.life/cvatt.html?get=Rm94U3BvcnRz",
    link3: "",
    link4: "",
    category: cat.sports,
  },
  {
    id: 25,
    name: "FOX SPORTS 2",
    img: "https://static.wikia.nocookie.net/logopedia/images/2/26/Fox_Sports_2_%28Argentina%29_2023.png/",
    link1: "https://blackface.world/dtvpl.html?id=1065",
    link2: "https://embed8.alandesk.life/cvatt.html?get=Rm94U3BvcnRzMkhE",
    link3: "",
    link4: "",
    category: cat.sports,
  },
  {
    id: 26,
    name: "FOX SPORTS 3",
    img: "https://static.wikia.nocookie.net/logopedia/images/8/83/Fox_Sports_3_%28Argentina%29_2023.png/",
    link1: "https://blackface.world/dtvpl.html?id=1066",
    link2: "https://embed8.alandesk.life/cvatt.html?get=Rm94U3BvcnRzM0hE",
    link3: "",
    link4: "",
    category: cat.sports,
  },
  {
    id: 27,
    name: "DSPORTS",
    img: "https://static.wikia.nocookie.net/logopedia/images/5/5a/DSports.png/",
    link1: "https://blackface.world/dtvpl.html?id=1057",
    link2: "https://www.tutelehdplayer.xyz/online.php?a=6",
    link3: "",
    link4: "",
    category: cat.sports,
  },
  {
    id: 28,
    name: "DSPORTS 2",
    img: "https://static.wikia.nocookie.net/logopedia/images/8/83/DSports2.png/",
    link1: "https://blackface.world/dtvpl.html?id=1063",
    link2: "https://www.tutelehdplayer.xyz/online.php?a=7",
    link3: "",
    link4: "",
    category: cat.sports,
  },
  {
    id: 29,
    name: "DSPORTS+",
    img: "https://static.wikia.nocookie.net/logopedia/images/4/45/DSportsM%C3%A1s.png/",
    link1: "https://blackface.world/dtvpl.html?id=1071",
    link2: "https://www.tutelehdplayer.xyz/online.php?a=8",
    link3: "",
    link4: "",
    category: cat.sports,
  },
  {
    id: 30,
    name: "HISTORY",
    img: "https://static.wikia.nocookie.net/logopedia/images/e/e8/History_2021.png/",
    link1: "https://blackface.world/dtvpl.html?id=1148",
    link2: "https://blackface.world/dtvpl.html?id=1148",
    link3: "",
    link4: "",
    category: cat.documental,
  },
  {
    id: 31,
    name: "HISTORY 2",
    img: "https://static.wikia.nocookie.net/logopedia/images/3/3a/History_2_%282022%29.png/",
    link1: "https://blackface.world/dtvpl.html?id=1147",
    link2: "https://blackface.world/dtvpl.html?id=1147",
    link3: "",
    link4: "",
    category: cat.documental,
  },
  {
    id: 32,
    name: "NATIONAL GEOGRAPHIC",
    img: "https://static.wikia.nocookie.net/logopedia/images/c/c6/National_Geographic_2008.svg/",
    link1: "https://blackface.world/dtvpl.html?id=1169",
    link2: "https://embed8.alandesk.life/cvatt.html?get=TmF0R2VvSEQ=",
    link3: "",
    link4: "",
    category: cat.documental,
  },
  {
    id: 33,
    name: "Discovery",
    img: "https://static.wikia.nocookie.net/logopedia/images/4/40/Discovery%2C_Inc_logo.svg/",
    link1:
      "https://player.twitch.tv/?channel=dt_yy83&parent=hdxchannel.xyz&parent=www.hdxchannel.xyz&parent=www.supertelevisionhd.com&parent=www.supertelevisionhd.net",
    link2: "https://embed8.alandesk.life/cvatt.html?get=RGlzY292ZXJ5SEQ=",
    link3: "",
    link4: "",
    category: cat.documental,
  },
  {
    id: 34,
    name: "Discovery Home & Health",
    img: "https://static.wikia.nocookie.net/logopedia/images/f/f3/Discovery_HnH_2022.svg/",
    link1: "https://blackface.world/dtvpl.html?id=1074",
    link2: "https://blackface.world/dtvpl.html?id=1074",
    link3: "",
    link4: "",
    category: cat.documental,
  },
  {
    id: 35,
    name: "Discovery ID",
    img: "https://static.wikia.nocookie.net/logopedia/images/5/58/CanalDiscoveryIDLA.png/",
    link1: "https://blackface.world/dtvpl.html?id=1076",
    link2: "https://blackface.world/dtvpl.html?id=1076",
    link3: "",
    link4: "",
    category: cat.documental,
  },
  {
    id: 36,
    name: "Discovery turbo",
    img: "https://static.wikia.nocookie.net/logopedia/images/a/ab/Discovery_Turbo_LatinAmerica_2021.svg/",
    link1: "https://blackface.world/dtvpl.html?id=1081",
    link2: "https://blackface.world/dtvpl.html?id=1081",
    link3: "",
    link4: "",
    category: cat.documental,
  },
  {
    id: 37,
    name: "HGTV",
    img: "https://static.wikia.nocookie.net/logopedia/images/a/a8/HGTV_2010.svg/",
    link1: "https://blackface.world/dtvpl.html?id=1144",
    link2: "https://blackface.world/dtvpl.html?id=1144",
    link3: "",
    link4: "",
    category: cat.documental,
  },
  {
    id: 38,
    name: "MAS CHiC",
    img: "https://static.wikia.nocookie.net/logopedia/images/e/e9/M%C3%A1s_Chic.svg/",
    link1: "https://blackface.world/dtvpl.html?id=1161",
    link2: "https://embed8.alandesk.life/cvatt.html?get=TWFzX0NoaWM=",
    link3: "",
    link4: "",
    category: cat.documental,
  },
  {
    id: 39,
    name: "DW",
    img: "https://static.wikia.nocookie.net/logopedia/images/7/75/Deutsche_Welle_symbol_2012.svg/",
    link1: "https://www.youtube.com/watch?v=tsStUN73_6I",
    link2:
      "https://canales.online/m3u8.html?get=aHR0cHM6Ly9kd2FtZHN0cmVhbTEwNC5ha2FtYWl6ZWQubmV0L2hscy9saXZlLzIwMTU1MzAvZHdzdHJlYW0xMDQvaW5kZXgubTN1OA==",
    link3: "",
    link4: "",
    category: cat.documental,
  },
  {
    id: 40,
    name: "Food Network",
    img: "https://static.wikia.nocookie.net/logopedia/images/5/59/FoodNetLogo.svg/",
    link1: "https://blackface.world/dtvpl.html?id=1113",
    link2: "https://embed8.alandesk.life/cvatt.html?get=Rm9vZF9OZXR3b3Jr",
    link3: "",
    link4: "",
    category: cat.documental,
  },
  {
    id: 41,
    name: "El Gourmet",
    img: "https://static.wikia.nocookie.net/logopedia/images/d/da/Elgourmet_23.svg/",
    link1: "https://blackface.world/dtvpl.html?id=1093",
    link2: "https://embed8.alandesk.life/cvatt.html?get=R291cm1ldA==",
    link3: "",
    link4: "",
    category: cat.documental,
  },
  {
    id: 42,
    name: "Flow Music",
    img: "https://static.wikia.nocookie.net/logopedia/images/0/0b/Flow_2021.svg/",
    link1: "https://embed8.alandesk.life/cvatt.html?get=Rmxvd19NdXNpY19YUA==",
    link2: "https://embed8.alandesk.life/cvatt.html?get=Rmxvd19NdXNpY18x",
    link3: "",
    link4: "",
    category: cat.music,
  },
  {
    id: 43,
    name: "Vorterix",
    img: "https://canales.online/img/logo_canal/Vorterix.png",
    link1:
      "https://www.youtube.com/embed/live_stream?channel=UCvCTWHCbBC0b9UIeLeNs8ug",
    link2: "https://www.youtube.com/watch?v=g7Kx0AKmfTg",
    link3: "",
    link4: "",
    category: cat.music,
  },
  {
    id: 44,
    name: "La 100 HD",
    img: "https://static.wikia.nocookie.net/logopedia/images/3/3a/La_100_fm.png/",
    link1: "https://www.youtube.com/watch?v=QgfoI5v0HNY",
    link2: "https://www.youtube.com/watch?v=QgfoI5v0HNY",
    link3: "",
    link4: "",
    category: cat.music,
  },
  {
    id: 45,
    name: "Radio Mitre",
    img: "https://4dproducciones.com.ar/wp-content/uploads/2020/10/Mitre.png",
    link1: "https://www.youtube.com/watch?v=fsd92RSrtLA",
    link2: "https://radiomitre.cienradios.com/player/mitre-am790/",
    link3: "",
    link4: "",
    category: cat.music,
  },
  {
    id: 46,
    name: "HBO",
    img: "https://static.wikia.nocookie.net/logopedia/images/c/c1/HBO.svg/",
    link1:
      "https://player.twitch.tv/?channel=bocx148&parent=onlinexlive.xyz&parent=www.onlinexlive.xyz&parent=www.supertelevisionhd.com&parent=www.supertelevisionhd.net",
    link2:
      "https://player.twitch.tv/?channel=bocx148&parent=onlinexlive.xyz&parent=www.onlinexlive.xyz&parent=www.supertelevisionhd.com&parent=www.supertelevisionhd.net",
    link3: "",
    link4: "",
    category: cat.movie,
  },
  {
    id: 47,
    name: "HBO 2",
    img: "https://static.wikia.nocookie.net/logopedia/images/c/c1/HBO.svg/",
    link1: "https://telefullenvivo.com/canales/hbo2/",
    link2: "https://telefullenvivo.com/canales/hbo2/op2.php",
    link3: "",
    link4: "",
    category: cat.movie,
  },
  {
    id: 48,
    name: "HBO+",
    img: "https://static.wikia.nocookie.net/logopedia/images/f/f9/Logohboplus2019.svg/",
    link1: "https://ok.ru/videoembed/6695123295815",
    link2:
      "https://player.twitch.tv/?channel=dt_yy83&parent=hdxchannel.xyz&parent=www.hdxchannel.xyz&parent=www.supertelevisionhd.com&parent=www.supertelevisionhd.net",
    link3: "",
    link4: "",
    category: cat.movie,
  },
  //   {
  //     id: 100,
  //     name: "",
  //     img: "",
  //     link1: "",
  //     link2: "",
  //     category: cat.adults,
  //   },
];

export const datosPrivtes = [
  {
    id: 49,
    name: "Playboy TV",
    img: "https://static.wikia.nocookie.net/logopedia/images/3/37/Playboy_TV_Logo.svg/",
    link1: "https://embed8.alandesk.life/cvatt.html?get=UGxheWJveQ",
    link2:
      "https://canales.online/m3u8.html?get=aHR0cHM6Ly9jZG5jZW50dXJ5LXBsYXlib3loZC56b2xlY2hhbWVkaWEubmV0L3BsYXlsaXN0Lm0zdTg=",
    category: cat.adults,
  },
  {
    id: 50,
    name: "Vanus",
    img: "https://static.wikia.nocookie.net/logopedia/images/c/cc/Venus_2014.svg/",
    link1: "https://embed8.alandesk.life/cvatt.html?get=VmVudXM=",
    link2:
      "https://canales.online/m3u8.html?get=aHR0cHM6Ly9jZG5jZW50dXJ5LXZlbnVzaGQuem9sZWNoYW1lZGlhLm5ldC9wbGF5bGlzdC5tM3U4",
    category: cat.adults,
  },
  {
    id: 51,
    name: "SeXtreme",
    img: "https://static.wikia.nocookie.net/logopedia/images/2/23/Sextreme.png/",
    link1: "https://latele-envivo.com/Embed/sextreme/op2.php",
    link2: "https://canales.online/en-vivo/sextreme/",
    category: cat.adults,
  },
  {
    id: 52,
    name: "Hustler HD",
    img: "https://static.wikia.nocookie.net/logopedia/images/1/12/Hustler_HD.png/",
    link1: "https://www.latele-envivo.com/Embed/hustler/",
    link2: "https://www.latele-envivo.com/Embed/hustler/",
    category: cat.adults,
  },
  {
    id: 53,
    name: "Brazzers",
    img: "https://static.wikia.nocookie.net/logopedia/images/3/32/Brazzers_TV_1.svg/",
    link1: "https://www.latele-envivo.com/Embed/brazzers/",
    link2: "https://www.latele-envivo.com/Embed/brazzers/",
    category: cat.adults,
  },
  {
    id: 54,
    name: "SEXY HOT",
    img: "http://login.sexyhot.com.br.s3-website-us-east-1.amazonaws.com/static/images/logo.png",
    link1: "https://www.latele-envivo.com/Embed/hot/",
    link2: "https://www.latele-envivo.com/Embed/hot/",
    category: cat.adults,
  },
  {
    id: 55,
    name: "Tushy Teens",
    img: "https://flyleafprint.com/wp-content/uploads/2021/11/Tushy-1.png",
    link1: "https://www.latele-envivo.com/Embed/teens/",
    link2: "https://www.latele-envivo.com/Embed/teens/",
    category: cat.adults,
  },
  {
    id: 56,
    name: "DORCEL",
    img: "https://static.wikia.nocookie.net/logopedia/images/b/be/Dorcel_TV_2022.svg/",
    link1: "https://www.latele-envivo.com/Embed/dorcel/",
    link2: "https://www.latele-envivo.com/Embed/dorcel/",
    category: cat.adults,
  },
  {
    id: 57,
    name: "Dream Sex",
    img: "https://static.wikia.nocookie.net/logopedia/images/0/09/XXXTentacion_2018.svg/",
    link1: "https://www.latele-envivo.com/Embed/dreamsex/",
    link2: "https://www.latele-envivo.com/Embed/dreamsex/",
    category: cat.adults,
  },
  {
    id: 58,
    name: "Proximo",
    img: "Private",
    link1: "#",
    link2: "#",
    category: cat.adults,
  },
];

//https://www.latele-envivo.com/
