let cat = {
  adults: "adults",
  documental: "docuemntal",
  news: "news",
  movie: "movie",
  music: "music",
  sports: "sports",
};
//"window-controls-overlay"
export const datos = [
  {
    id: 1,
    name: "Canal 2 Jujuy",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/canal2Jujuy.webp",
    link1:
      "https://livestream.com/accounts/679322/events/3782013/player?width=640&height=360&autoPlay=true&mute=false",
    link2: "",
    link3: "",
    link4: "",
    category: cat.news,
  },
  {
    id: 2,
    name: "Canal 4 Jujuy",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/Canal4Jujuy.webp",
    link1: "https://canal4jujuy.elcuatro.com//player/index?autoplay=true",
    link2: "",
    link3: "",
    link4: "",
    category: cat.news,
  },
  {
    id: 3,
    name: "Canal 7 Jujuy",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/Canal7Jujuy.webp",
    link1: "https://arcast.com.ar/canal7jujuy/",
    link2: "https://canal7dejujuy.com.ar/",
    link3: "",
    link4: "",
    category: cat.news,
  },
  {
    id: 4,
    name: "Telefe",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/Telefe.webp",
    link1: "https://embed8.alandesk.life/cvatt.html?get=VGVsZWZlSEQ=&lang=1",
    link2: "https://mitelefe.com/vivo",
    link3: "https://blackface.world/dtvpl.html?id=1216",
    link4:
      "https://nosequewea.tk/dtvc?get=aHR0cHM6Ly9kdHZvdHQtYWJjLmFrYW1haXplZC5uZXQvZGFzaF9saXZlXzEyMTYvbWFuaWZlc3QubXBk&key=ZDgzZTJlMGNiOTczNWJlYTlmYzlmMGI5MGNlYTFlMTQ=&key2=NDEyNWU0MDgwMGEwOGJiYzY2Y2YyNzc1NmE1YWIyODM=",
    category: cat.news,
  },
  {
    id: 5,
    name: "TN",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/TN.webp",
    link1: "https://www.youtube.com/embed/HPiv1pzIPRc?autoplay=true",
    link2: "",
    link3: "https://embed8.alandesk.life/cvatt.html?get=VG9kb05vdGljaWFz",
    link4: "https://blackface.world/dtvpl.html?id=1225", //"https://www.latele-envivo.com/Embed/tn/op2.php",
    category: cat.news,
  },
  {
    id: 6,
    name: "El Trece",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/ElTrece.webp",
    link1: "https://blackface.world/dtvpl.html?id=1095",
    link2: "",
    link3: "https://embed8.alandesk.life/cvatt.html?get=QXJ0ZWFySEQ",
    link4: "",
    category: cat.news,
  },
  {
    id: 7,
    name: "LN+",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/LNplus.webp",
    link1: "https://www.youtube.com/embed/4e8Iw3Frf1A?autoplay=true",
    link2: "https://lnmas.lanacion.com.ar/",
    link3: "https://blackface.world/dtvpl.html?id=1154",
    link4: "https://embed8.alandesk.life/cvatt.html?get=TGFfTmFjaW9u",
    category: cat.news,
  },
  {
    id: 8,
    name: "América",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/America.webp",
    link1: "https://www.americatv.com.ar/vivo",
    link2: "",
    link3: "https://blackface.world/dtvpl.html?id=1010",
    link4: "https://embed8.alandesk.life/cvatt.html?get=QW1lcmljYVRW",
    category: cat.news,
  },
  {
    id: 9,
    name: "A24",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/A24.webp",
    link1: "https://www.youtube.com/embed/QGpHLgRnrx4?autoplay=true",
    link2: "https://www.a24.com/vivo",
    link3: "https://blackface.world/dtvpl.html?id=1009",
    link4: "https://embed8.alandesk.life/cvatt.html?get=QW1lcmljYTI0",
    category: cat.news,
  },
  {
    id: 10,
    name: "Canal 26",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/Canal26.webp",
    link1: "https://www.youtube.com/embed/2IfTdw28WFY?autoplay=true",
    link2: "https://www.canal26.com/canal26-en-vivo",
    link3: "https://blackface.world/dtvpl.html?id=1031",
    link4: "https://embed8.alandesk.life/cvatt.html?get=MjZfVFZfSEQ",
    category: cat.news,
  },
  {
    id: 11,
    name: "El Nueve ",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/elnueve.webp",
    link1: "https://www.elnueve.com.ar/en-vivo",
    link2: "",
    link3: "https://blackface.world/dtvpl.html?id=1032",
    link4: "https://embed8.alandesk.life/cvatt.html?get=Q2FuYWw5",
    category: cat.news,
  },
  {
    id: 12,
    name: "C5N",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/C5N.webp",
    link1: "https://www.youtube.com/embed/-FwrJbV-KDo?autoplay=true",
    link2: "https://www.c5n.com/vivo",
    link3: "https://blackface.world/dtvpl.html?id=1028",
    link4: "https://embed8.alandesk.life/cvatt.html?get=QzVO",
    category: cat.news,
  },
  {
    id: 13,
    name: "TV Pública",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/TVP.webp",
    link1: "https://embed8.alandesk.life/cvatt.html?get=Q2FuYWw3",
    link2: "https://blackface.world/dtvpl.html?id=1156",
    link3: "",
    link4: "",
    category: cat.news,
  },
  {
    id: 14,
    name: "Crónica HD",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/Cronica.webp",
    link1: "https://www.youtube.com/embed/avly0uwZzOE?autoplay=true",
    link2: "https://www.cronica.com.ar/cronica-en-vivo", //https://vmf.edge-apps.net/embed/live.php?streamname=cronicatv_video1-100044&autoplay=true",
    link3: "https://embed8.alandesk.life/cvatt.html?get=Q3JvbmljYVRW",
    category: cat.news,
  },
  {
    id: 15,
    name: "CNN",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/CNN.webp",
    link1:
      "https://nosequewea.tk/fl?get=LmN2YXR0di5jb20uYXIvbGl2ZS9jNmVkcy9DTk5fZW5fRXNwYW5vbC9TQV9MaXZlX2Rhc2hfZW5jL0NOTl9lbl9Fc3Bhbm9sLm1wZA==&key=MGIyMGVkOWRhMGU1NDU3YzlkZmQzYWUwYjYwOTI0OTE=&key2=OTg5OTdhNzAyMGMxOGNiMjgxNzRhMjQ5MDE0NzgzMGE=",
    link3: "",
    category: cat.news,
  },
  {
    id: 16,
    name: "RT ESPAÑOL",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/rt.webp",
    link1:
      "https://canales.online/m3u8.html?get=aHR0cHM6Ly9ydC1lc3AucnR0di5jb20vbGl2ZS9ydGVzcC9wbGF5bGlzdC5tM3U4",
    link3:
      "https://megatelevisiontv.live/hls.html?get=aHR0cHM6Ly9ydC1lc3AucnR0di5jb20vbGl2ZS9ydGVzcC9wbGF5bGlzdC5tM3U4",
    category: cat.news,
  },
  {
    id: 17,
    name: "STAR+",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/starplus.webp",
    link1: "https://librefutboltv.com/star-plus/",
    link2: "",
    link3: "https://canales.online/star-plus/",
    link4: "https://deportestvhd.com/star-plus.html",
    category: cat.sports,
  },
  {
    id: 18,
    name: "ESPN",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/ESPN.webp",
    link1: "https://embed8.alandesk.life/cvatt.html?get=RVNQTjJIRA&lang=1",
    link2: "",
    link3: "https://blackface.world/dtvpl.html?id=1104",
    link4: "https://futbolfullenvivo.nl/canales/espn/",
    category: cat.sports,
  },
  {
    id: 19,
    name: "ESPN 2",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/ESPN2.webp",
    link1: "https://embed8.alandesk.life/cvatt.html?get=RVNQTjJfQXJn",
    link2: "",
    link3: "https://blackface.world/dtvpl.html?id=1099",
    link4: "https://futbolfullenvivo.nl/canales/espn2/",
    category: cat.sports,
  },
  {
    id: 20,
    name: "ESPN 3",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/ESPN3.webp",
    link1: "https://embed8.alandesk.life/cvatt.html?get=RVNQTjM",
    link2: "",
    link3: "https://blackface.world/dtvpl.html?id=1103",
    link4: "https://futbolfullenvivo.nl/canales/espn3/",
    category: cat.sports,
  },
  {
    id: 21,
    name: "ESPN 4",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/ESPN4.webp",
    link1: "https://futbolfullenvivo.nl/canales/espn4/",
    link2: "",
    link3: "https://futbolfullenvivo.nl/canales/espn4/op2.php",
    category: cat.sports,
  },
  {
    id: 22,
    name: "ESPN EXTRA",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/ESPN_Extra.webp",
    link1: "https://embed8.alandesk.life/cvatt.html?get=RVNQTkhE",
    link2: "",
    link3: "https://blackface.world/dtvpl.html?id=1107",
    link4: "https://futbolfullenvivo.nl/canales/espnextra/",
    category: cat.sports,
  },
  {
    id: 23,
    name: "ESPN PREMIUM",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/ESPN_Premium.webp",
    link1:
      "https://embed8.alandesk.life/cvatt.html?get=Rm94X1Nwb3J0c19QcmVtaXVuX0hE&lang=1",
    link2: "",
    link3: "https://blackface.world/dtvpl.html?id=1125&lang=1",
    link4: "https://futbolfullenvivo.nl/canales/espn-premium/",
    category: cat.sports,
  },
  {
    id: 24,
    name: "TNT SPORTS",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/TNTSports.webp",
    link1: "https://embed8.alandesk.life/cvatt.html?get=VE5UX1Nwb3J0c19IRA",
    link2: "",
    link3: "https://blackface.world/dtvpl.html?id=1233",
    link4: "https://futbolfullenvivo.nl/canales/tnt-sports/",
    category: cat,
  },
  {
    id: 25,
    name: "TyC Sports",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/TyCSports.webp",
    link1: "https://embed8.alandesk.life/cvatt.html?get=VHlDU3BvcnQ",
    link2: "",
    link3: "https://blackface.world/dtvpl.html?id=1240",
    link4: "https://futbolfullenvivo.nl/canales/tyc/",
    category: cat.sports,
  },
  {
    id: 26,
    name: "FOX SPORTS",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/FoxSports.webp",
    link1: "https://embed8.alandesk.life/cvatt.html?get=Rm94U3BvcnRz",
    link2: "",
    link3: "https://blackface.world/dtvpl.html?id=1118",
    link4: "https://futbolfullenvivo.nl/canales/fox-sports/",
    category: cat.sports,
  },
  {
    id: 27,
    name: "FOX SPORTS 2",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/FoxSports2.webp",
    link1: "https://embed8.alandesk.life/cvatt.html?get=Rm94U3BvcnRzMkhE",
    link2: "",
    link3: "https://embed47.thaidomains.co.in/cvatt.html?get=Rm94U3BvcnRzMkhE", //"https://my7mv.deportelibre.live/player?channelId=8a782cdd-35e7-4a57-b687-893a6d5a4f4e",
    category: cat.sports,
  },
  {
    id: 28,
    name: "FOX SPORTS 3",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/FoxSports3.webp",
    link1: "https://embed8.alandesk.life/cvatt.html?get=Rm94U3BvcnRzM0hE",
    link2: "",
    link3: "https://embed47.thaidomains.co.in/cvatt.html?get=Rm94U3BvcnRzM0hE",
    link4: "",
    category: cat.sports,
  },
  {
    id: 29,
    name: "DSPORTS",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/DSports.webp",
    link1: "https://bestformula.one/dtvpl2.html?id=1057&lang=1",
    link2: "",
    link3: "https://blackface.world/dtvpl.html?id=1057",
    link4: "",
    category: cat.sports,
  },
  {
    id: 30,
    name: "DSPORTS 2",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/DSports2.webp",
    link1: "https:///bestformula.one/dtvpl2.html?id=1063&lang=1",
    link2: "",
    link3: "https://blackface.world/dtvpl.html?id=1063",
    link4: "https://futbolfullenvivo.nl/canales/directv-sports2/",
    category: cat.sports,
  },
  {
    id: 31,
    name: "DSPORTS+",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/DSports+.webp",
    link1: "https://bestformula.one/dtvpl2.html?id=1071",
    link2: "",
    link3: "https://blackface.world/dtvpl.html?id=1071",
    link4: "https://futbolfullenvivo.nl/canales/directv-sports-plus/",
    category: cat.sports,
  },
  {
    id: 32,
    name: "DSPORTS FIGHT",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/dsportsfight.webp",
    link1:
      "https://germanyip.work/sv-mt.php?get=aHR0cHM6Ly9kdHZvdHQtYWJjLmFrYW1haXplZC5uZXQvZGFzaF9saXZlXzEyNTkvbWFuaWZlc3QubXBk&key=MzZiMmM2Yjc3MzZhNTkwMWJmNDA4OTE2YTQ1NGFiZjk=&key2=ZjBkMjI1NGY4NWI3MzcxN2Y0YzJjZDgxYmRhNzE4ODk",
    link2: "",
    link3: "",
    link4: "",
    category: cat.sports,
  },
  {
    id: 33,
    name: "DSPORTS MOTOR",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/dsportsmotor.webp",
    link1:
      "https://megadeportes.xyz/repro.html?r=Ly9nZXJtYW55aXAud29yay9zdi1tdC5waHA/Z2V0PWFIUjBjSE02THk5a2RIWnZkSFF0WVdKakxtRnJZVzFoYVhwbFpDNXVaWFF2WkdGemFGOXNhWFpsWHpFeU56a3ZiV0Z1YVdabGMzUXViWEJrJmtleT1PRFkxTXpGaE9UTXdOV1EyTldOaU56aGlNVGhpTW1NeE5EQXlORE15TUdVPSZrZXkyPVpXRmpNakkwWVdRd1pUSTBPVE0zTURObU5Ea3hZekZoTXpneU1UUmpNV0k9",
    link2: "",
    link3: "",
    link4: "",
    category: cat.sports,
  },
  {
    id: 34,
    name: "HISTORY",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/History.webp",
    link1: "https://blackface.world/dtvpl.html?id=1148",
    link2: "",
    link3: "https://www.latele-envivo.com/Embed/history/",
    link4: "https://www.latele-envivo.com/Embed/history/op2.php",
    category: cat.documental,
  },
  {
    id: 35,
    name: "HISTORY 2",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/History2.webp",
    link1: "https://blackface.world/dtvpl.html?id=1147",
    link2: "",
    link3: "https://www.latele-envivo.com/Embed/history2/",
    link4: "https://www.latele-envivo.com/Embed/history2/op2.php",
    category: cat.documental,
  },
  {
    id: 36,
    name: "NATIONAL GEOGRAPHIC",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/NationalGeographic.webp",
    link1: "https://blackface.world/dtvpl.html?id=1169",
    link2: "",
    link3: "https://www.latele-envivo.com/Embed/national-geographic/",
    link4: "https://embed8.alandesk.life/cvatt.html?get=TmF0R2VvSEQ=",
    category: cat.documental,
  },
  {
    id: 37,
    name: "Discovery",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/Discovery.webp",
    link1:
      "https://nosequewea.tk/dtvc?get=Ly9kdHZvdHQtY2JjLmFrYW1haXplZC5uZXQvZGFzaF9saXZlXzEwNzMvbWFuaWZlc3QubXBk&key=ODJmN2FhYWU0OWU1NTZjMTk4NWRhMDQ2MjMzN2RmNDM=&key2=NzZiMTNmZDhhMjk4ZDE4OGFjNTI1MjM4N2IyMjg2ODc=",
    link2: "https://megatelevisiontv.live/en-vivo/discovery/",
    link3:
      "https://nosequewea.tk/fl?get=LmN2YXR0di5jb20uYXIvbGl2ZS9jM2Vkcy9EaXNjb3ZlcnlIRC9TQV9MaXZlX2Rhc2hfZW5jXzJBL0Rpc2NvdmVyeUhELm1wZA==&key=YzI4M2M4NGE3YWYwZDdjOGI5YjYxMmE4ZmIyMmEwMDE=&key2=ZjQ1NTEwYzcyMWVlYmQ2ZWFhODZhMmUxNmNjYmQ3N2Q=",
    link4: "",
    category: cat.documental,
  },
  {
    id: 38,
    name: "Discovery Home & Health",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/DiscoveryH%26H.webp",
    link1: "https://blackface.world/dtvpl.html?id=1074",
    link2: "",
    link3: "https://www.latele-envivo.com/Embed/discovery-hh/",
    link4: "",
    category: cat.documental,
  },
  {
    id: 39,
    name: "Discovery ID",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/DiscoveryID.webp",
    link1: "https://blackface.world/dtvpl.html?id=1076",
    link2: "",
    link3: "https://www.latele-envivo.com/Embed/discovery-investigacion/",
    link4: "",
    category: cat.documental,
  },
  {
    id: 40,
    name: "Discovery Science",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/DiscoveryScience.webp",
    link1:
      "https://nosequewea.tk/fl?get=LmN2YXR0di5jb20uYXIvbGl2ZS9jNmVkcy9EaXNjb3ZlcnlfU2NpZW5jZS9TQV9MaXZlX2Rhc2hfZW5jXzJBL0Rpc2NvdmVyeV9TY2llbmNlLm1wZA==&key=NDZiYTQwOWZiMDRlNDBmYjg2YjQ2NmQ5N2UzYTk1ODg=&key2=ZjEyOWZiOWI1ZDIxM2UyMGUyYWJlNTI5YjhjZjI1OTc=",
    link2: "",
    link3: "",
    link4: "",
    category: cat.documental,
  },
  {
    id: 41,
    name: "Discovery turbo",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/DiscoveryTurbo.webp",
    link1: "https://blackface.world/dtvpl.html?id=1081",
    link2: "",
    link3: "https://www.latele-envivo.com/Embed/discovery-turbo/",
    link4: "",
    category: cat.documental,
  },
  {
    id: 42,
    name: "HGTV",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/HGTV.webp",
    link1: "https://blackface.world/dtvpl.html?id=1144",
    link2: "",
    link3: "https://www.latele-envivo.com/Embed/discovery-hgtv/",
    link4: "https://www.latele-envivo.com/Embed/discovery-hgtv/op2.php",
    category: cat.documental,
  },
  {
    id: 43,
    name: "MAS CHiC",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/MasChic.webp",
    link1: "https://embed8.alandesk.life/cvatt.html?get=TWFzX0NoaWM=",
    link2: "",
    link3: "https://blackface.world/dtvpl.html?id=1161",
    link4: "https://www.latele-envivo.com/Embed/mas-chic/op2.php",
    category: cat.documental,
  },
  {
    id: 44,
    name: "DW",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/DeutscheWelle.webp",
    link1: "https://www.youtube.com/embed/tsStUN73_6I?autoplay=true",
    link2: "",
    link3:
      "https://canales.online/m3u8.html?get=aHR0cHM6Ly9kd2FtZHN0cmVhbTEwNC5ha2FtYWl6ZWQubmV0L2hscy9saXZlLzIwMTU1MzAvZHdzdHJlYW0xMDQvaW5kZXgubTN1OA==",
    link4: "",
    category: cat.documental,
  },
  {
    id: 45,
    name: "TRU TV",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/TruTV.webp",
    link1: "https://crytonep.github.io/mtonline/trutv.html",
    link2: "",
    link3: "",
    link4: "",
    category: cat.documental,
  },
  {
    id: 46,
    name: "SUN",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/Sun.webp",
    link1: "https://megatelevisiontv.live/en-vivo/sun-channel/",
    link2: "",
    link3: "https://canales.online/en-vivo/sun-channel/",
    link4: "",
    category: cat.documental,
  },
  {
    id: 47,
    name: "Food Network",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/FoodNetwork.webp",
    link1: "https://embed8.alandesk.life/cvatt.html?get=Rm9vZF9OZXR3b3Jr",
    link2: "",
    link3: "https://blackface.world/dtvpl.html?id=1113",
    link4: "https://www.latele-envivo.com/Embed/food-network/",
    category: cat.documental,
  },
  {
    id: 48,
    name: "El Gourmet",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/Elgourmet.webp",
    link1: "https://embed8.alandesk.life/cvatt.html?get=R291cm1ldA==",
    link2: "",
    link3: "https://blackface.world/dtvpl.html?id=1093",
    link4:
      "https://nosequewea.tk/fl?get=LmN2YXR0di5jb20uYXIvbGl2ZS9jM2Vkcy9Hb3VybWV0L1NBX0xpdmVfZGFzaF9lbmMvR291cm1ldC5tcGQ=&key=OTNkODUzYWM0YzhlMjRjZjAyOTVmNmY5N2VlNTNiZDM=&key2=ZmE1ODE3ZmFiNGZiMDU0Y2NlYTFhYmI5ZjNkNzY3ZWQ=",
    category: cat.documental,
  },
  {
    id: 49,
    name: "Flow Music",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/flowmusic.webp",
    link1: "https://embed8.alandesk.life/cvatt.html?get=Rmxvd19NdXNpY19YUA==",
    link2: "",
    link3:
      "https://nosequewea.tk/fl?get=LmN2YXR0di5jb20uYXIvbGl2ZS9jN2Vkcy9GbG93X011c2ljX1hQL1NBX0xpdmVfZGFzaF9lbmNfMkEvRmxvd19NdXNpY19YUC5tcGQ=&key=YjJhYWU0NGE3NDE0NGJlOGIyMTE4ZTIwZDE0MTJiYWI=&key2=OGE3YWU5OTZkMTJkOGQ1ZDU2MzdkMTA0NGY4ZTA4Yjc=",
    link4: "https://embed8.alandesk.life/cvatt.html?get=Rmxvd19NdXNpY18x",
    category: cat.music,
  },
  {
    id: 50,
    name: "Vorterix",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/Vorterix.webp",
    link1: "https://www.youtube.com/embed/g7Kx0AKmfTg?autoplay=true",
    link3: "",
    link4: "",
    category: cat.music,
  },
  {
    id: 51,
    name: "LUZZU TV",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/LUZZU.webp",
    link1: "http://luzutv.com.ar/",
    link2: "",
    link3:
      "https://player.twitch.tv/?channel=luzu_tv&&parent=https://marctv.vercel.app/",
    link4:
      "https://player.twitch.tv/?channel=luzu_tv&parent=marctv.vercel.app/",
    category: cat.music,
  },
  {
    id: 52,
    name: "La 100 HD",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/La100.webp",
    link1: "https://la100.cienradios.com/hd/",
    link2: "https://www.youtube.com/embed/nDqin3S5wi8?autoplay=true",
    link3: "",
    category: cat.music,
  },
  {
    id: 53,
    name: "Radio Mitre",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/Mitre.webp",
    link1: "https://www.youtube.com/embed/Q7WafLrEroA?autoplay=true",
    link2: "https://radiomitre.cienradios.com/hd/",
    link3: "",
    link4: "",
    category: cat.music,
  },
  {
    id: 54,
    name: "TCM",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/TCM.webp",
    link1: "https://www.latele-envivo.com/Embed/tcm/op2.php",
    link3: "https://crytonep.github.io/mtonline/tcm.html",
    link4: "",
    category: cat.movie,
  },
  {
    id: 55,
    name: "HBO",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/HBO.webp",
    link1: "https://www.latele-envivo.com/Embed/hbo/op2.php",
    link2: "https://www.latele-envivo.com/Embed/hbo/",
    link3:
      "https://nosequewea.tk/dtvc?get=Ly9kdHZvdHQtYWJjLmFrYW1haXplZC5uZXQvZGFzaF9saXZlXzExNDAvbWFuaWZlc3QubXBk&key=OTllZWZjMDY4ZGIzNTA5YjlmMGNmNWIzNDExNDIxOWQ=&key2=NmMyM2UzMWE0ZDgzYjU2OGU4NGFlYzYwOWE2M2ViYzk=",
    link4:
      "https://nosequewea.tk/dtvc?get=Ly9kdHZvdHQtYWJjLmFrYW1haXplZC5uZXQvZGFzaF9saXZlXzExNDAvbWFuaWZlc3QubXBk&key=OTllZWZjMDY4ZGIzNTA5YjlmMGNmNWIzNDExNDIxOWQ=&key2=NmMyM2UzMWE0ZDgzYjU2OGU4NGFlYzYwOWE2M2ViYzk=",
    category: cat.movie,
  },
  {
    id: 56,
    name: "HBO 2",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/HBO2.webp", ///
    link1: "https://telefullenvivo.com/canales/hbo2/",
    link2: "",
    link3: "https://telefullenvivo.com/canales/hbo2/op2.php",
    link4: "",
    category: cat.movie,
  },
  {
    id: 57,
    name: "HBO+",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/HBOplus.webp",
    link1:
      "https://nosequewea.tk/dtvc?get=aHR0cHM6Ly9kdHZvdHQtYWJjLmFrYW1haXplZC5uZXQvZGFzaF9saXZlXzExNDEvbWFuaWZlc3QubXBk&key=Njc5NWEzMDNhOWU4NTE3ZmJjYTM4Mzc2YzBhZjJmNzY=&key2=MWJkYjMxNzIyOTA2NmFkMmQ3NGM0ODE0YTEzOGUxMzY=",
    link2:
      "https://nosequewea.tk/fl?get=LmN2YXR0di5jb20uYXIvbGl2ZS9jNmVkcy9IQk9fUGx1cy9TQV9MaXZlX2Rhc2hfZW5jL0hCT19QbHVzLm1wZA==&key=ZjBlN2Y3ZDQ1ODk5MGVkZmFiN2I5OGI0MTI1NjQ2MTU=&key2=NzkyMDU3NTRiN2Y4NGE2MjY2MWMyZGJlOWRlNWRkNWQ=",
    link3: "https://ok.ru/videoembed/6695123295815",
    link4: "",
    category: cat.movie,
  },
  {
    id: 58,
    name: "HBO EXTREME",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/HBOXtreme.webp",
    link1: "https://www.latele-envivo.com/Embed/hbo-xtreme/",
    link3:
      "https://nosequewea.tk/fl?get=LmN2YXR0di5jb20uYXIvbGl2ZS9jNmVkcy9IQk9fRXh0cmVtZS9TQV9MaXZlX2Rhc2hfZW5jL0hC%20T19FeHRyZW1lLm1wZA==&key=ZDUwNDAxMWJiZWY0NjdjMGRlM2E3NTM0ZTMwMmE2ZDQ=&key2=MzM0MTAzZTJhYmUxNmZhYTdmOWFiMmUzMDk3YzVhNTg=",
    category: cat.movie,
  },
  {
    id: 59,
    name: "SONY",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/SonyChannel.webp",
    link1: "https://blackface.world/dtvpl.html?id=1190",
    link3:
      "https://nosequewea.tk/dtvc?get=Ly9kdHZvdHQtY2JjLmFrYW1haXplZC5uZXQvZGFzaF9saXZlXzExOTAvbWFuaWZlc3QubXBk&key=MTAxMGI5OWZiMTI0NTQwYWFhNDc1YTQxMjU5NzUxZWI=&key2=MTk3NWM2YmNjOTU2NmE2ZTk0YWIyNjNkYzhmMDRiNTc=",
    link4: "https://www.latele-envivo.com/Embed/sony/",
    category: cat.movie,
  },
  {
    id: 60,
    name: "SONY MOVIES",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/SonyMovies.webp",
    link1:
      "https://nosequewea.tk/dtvc?get=Ly9kdHZvdHQtYWJjLmFrYW1haXplZC5uZXQvZGFzaF9saXZlXzEyNjMvbWFuaWZlc3QubXBk&key=MzkxYzEzNzAzNGYwNTM5MzhlZGJmMjY3OTk1NDlkZGM=&key2=MTlkNjQzZDhhNTBiMmY4MjljOTZhODk3ZjdkZjI1NWQ=",
    link3: "https://megatelevisiontv.live/en-vivo/sony-movies/",
    link4: "",
    category: cat.movie,
  },
  {
    id: 61,
    name: "Warner TV",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/Warner.webp",
    link1:
      "https://nosequewea.tk/dtvc?get=aHR0cHM6Ly9kdHZvdHQtY2JjLmFrYW1haXplZC5uZXQvZGFzaF9saXZlXzEyNDgvbWFuaWZlc3QubXBk&key=NTZhMjQ3MzJjN2M1NThhMGIyNDRkYzlkNWY5MTBmODc=&key2=NjFkZmVmODFjZWUxMWNiNDE5YTYxMjAyNzBiOTU4N2I=",
    link3: "https://blackface.world/dtvpl.html?id=1248",
    link4:
      "https://nosequewea.tk/fl?get=LmN2YXR0di5jb20uYXIvbGl2ZS9jN2Vkcy9XYXJuZXJIRC9TQV9MaXZlX2Rhc2hfZW5jXzJBL1dhcm5lckhELm1wZA==&key=MDY5YmQzZjBiNmMyNzk0NjdlMDg1NDlmMTdiZjViZDA=&key2=NWFmYTdlMzY5YTZkZTEwOTM4MThhODVhZjkxMmE3NzU=",
    category: cat.movie,
  },
  {
    id: 62,
    name: "UNIVERSAL PREMIERE",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/UniversalPremiere.webp",
    link1:
      "https://nosequewea.tk/dtvc?get=aHR0cHM6Ly9kdHZvdHQtYWJjLmFrYW1haXplZC5uZXQvZGFzaF9saXZlXzEyNTYvbWFuaWZlc3QubXBk&key=ZDA4MGJlMjhhMGZjNTk3MGJmMWRlODk3ZjgwZDQwYmQ=&key2=YWI4MTg3ZDUwZDMxMWQzMGJjMGQ3ZGM2ZWI1Njk3ZDE=",
    link3: "https://www.latele-envivo.com/Embed/universal-premiere/",
    link4: "https://megatelevisiontv.live/en-vivo/universal-premiere/",
    category: cat.movie,
  },
  {
    id: 63,
    name: "UNIVERSAL CINEMA",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/UniversalCinema.webp",
    link1: "https://www.latele-envivo.com/Embed/universal-cinema/",
    link3:
      "https://nosequewea.tk/dtvc?get=aHR0cHM6Ly9kdHZvdHQtYWJjLmFrYW1haXplZC5uZXQvZGFzaF9saXZlXzEyNTMvbWFuaWZlc3QubXBk&key=Y2UwYTdjODgzZTJhNTQzMGJiYTk3YTNkNjhlMGRhZjg=&key2=ZTMwZGQ0OTA4ZTY2NzYzNzM2OWRmYjY1ODJmNTRkNjQ=",
    link4: "https://www.latele-envivo.com/Embed/universal-cinema/",
    category: cat.movie,
  },
  {
    id: "adultos/64",
    name: "ADULTOS",
    img: "https://static.wikia.nocookie.net/logopedia/images/8/8c/PEGI_Sex.svg/",
    link1: "",
    category: cat.adults,
  },
];

export const datosPrivates = [
  {
    id: 64,
    name: "Playboy TV",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/PlayboyTV.webp",
    link1: "https://embed8.alandesk.life/cvatt.html?get=UGxheWJveQ",
    link2: "https://www.latele-envivo.com/Embed/playboy/",
    category: cat.adults,
  },
  {
    id: 65,
    name: "Venus",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/Venus.webp",
    link1: "https://embed8.alandesk.life/cvatt.html?get=VmVudXM=",
    link2:
      "https://canales.online/m3u8.html?get=aHR0cHM6Ly9jZG5jZW50dXJ5LXZlbnVzaGQuem9sZWNoYW1lZGlhLm5ldC9wbGF5bGlzdC5tM3U4",
    category: cat.adults,
  },
  {
    id: 66,
    name: "SeXtreme",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/Sextreme.webp",
    link1: "https://latele-envivo.com/Embed/sextreme/op2.php",
    link2: "https://www.latele-envivo.com/Embed/sextreme/op2.php",
    category: cat.adults,
  },
  {
    id: 67,
    name: "Hustler HD",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/HustlerHD.webp",
    link1: "https://www.latele-envivo.com/Embed/hustler/",
    link2: "https://megatelevisiontv.live/en-vivo/hustler/",
    category: cat.adults,
  },
  {
    id: 68,
    name: "Brazzers",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/BrazzersTV.webp",
    link1: "https://www.latele-envivo.com/Embed/brazzers/",
    category: cat.adults,
  },
  {
    id: 69,
    name: "SEXY HOT",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/sexyhot.webp",
    link1: "https://www.latele-envivo.com/Embed/hot/",
    link2: "https://megatelevisiontv.live/en-vivo/sexyhot/",
    category: cat.adults,
  },
  {
    id: 70,
    name: "Tushy Teens",
    img: "https://static.wixstatic.com/media/dc5d85_369bb4a9a7c8409db0285b8436778077~mv2_d_3000_1319_s_2.png/v1/fill/w_894,h_393,al_c,usm_0.66_1.00_0.01/Teenager%20LOGO%20New%20Transparent.png",
    link1: "https://www.latele-envivo.com/Embed/teens/",
    category: cat.adults,
  },
  {
    id: 71,
    name: "DORCEL",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/DorcelTV.webp",
    link1: "https://www.latele-envivo.com/Embed/dorcel/",
    category: cat.adults,
  },
  {
    id: 72,
    name: "Dream Sex",
    img: "https://static.wikia.nocookie.net/logopedia/images/0/09/XXXTentacion_2018.svg/",
    link1: "https://www.latele-envivo.com/Embed/dreamsex/",
    category: cat.adults,
  },
  {
    id: 73,
    name: "Private",
    img: "https://raw.githubusercontent.com/marco5x/marcTV/master/src/assets/PRIVATE.webp",
    link1: "https://megatelevisiontv.live/en-vivo/private/",
    link2: "#",
    category: cat.adults,
  },
];

//https://www.latele-envivo.com/
//https://sfntv.xyz/inicio
//https://megatelevisiontv.live/
//https://cabletvhd.xyz/
//https://canales.online/
