let cat = {
  adults: "adults",
  documental: "docuemntal",
  news: "news",
  movie: "movie",
  music: "music",
  sports: "sports",
};

export const datos = [
  {
    id: 1,
    name: "Canal 2 (Perico)",
    img: "http://canal2perico.com.ar/canal2/images/logo.png",
    link1: "https://streamcasthd.com:2020/VideoPlayer/tecnovisioncanal2tv",
    link2: "",
    link3: "",
    category: cat.news,
  },
  {
    id: 2,
    name: "Canal 2 Jujuy",
    img: "http://canal2jujuy.com/canal2/wp-content/uploads/2020/02/logoc2fw.png",
    link1:
      "https://livestream.com/accounts/679322/events/3782013/player?width=640&height=360&autoPlay=true&mute=false",
    link2: "",
    link3: "",
    link4: "",
    category: cat.news,
  },
  {
    id: 3,
    name: "Canal 4 Jujuy",
    img: "https://i0.wp.com/directostv.teleame.com/wp-content/uploads/2016/05/Canal-4-Jujuy-en-vivo-Online.png?resize=1068%2C601&ssl=1",
    link1: "https://canal4jujuy.elcuatro.com/",
    link2: "",
    link3: "",
    link4: "",
    category: cat.news,
  },
  {
    id: 4,
    name: "Canal 7 Jujuy",
    img: "https://static.wikia.nocookie.net/logopedia/images/4/4c/Canal_Siete_Jujuy_%28Logo_2020_-_2%29.png/",
    link1: "https://arcast.com.ar/canal7jujuy/",
    link2: "https://canal7dejujuy.com.ar/",
    link3: "",
    link4: "",
    category: cat.news,
  },
  {
    id: 5,
    name: "Telefe",
    img: "https://static.wikia.nocookie.net/logopedia/images/0/01/Telefe_2018_3D.svg/",
    link1: "https://test01.cloud.telefe.com/vivo/",
    link2: "", //"https://nosequewea.tk/dtvc?get=aHR0cHM6Ly9kdHZvdHQtYWJjLmFrYW1haXplZC5uZXQvZGFzaF9saXZlXzEyMTYvbWFuaWZlc3QubXBk&key=ZDgzZTJlMGNiOTczNWJlYTlmYzlmMGI5MGNlYTFlMTQ=&key2=NDEyNWU0MDgwMGEwOGJiYzY2Y2YyNzc1NmE1YWIyODM=",
    link3: "https://blackface.world/dtvpl.html?id=1216",
    link4: "https://embed8.alandesk.life/cvatt.html?get=VGVsZWZlSEQ=&lang=1",
    category: cat.news,
  },
  {
    id: 6,
    name: "TN",
    img: "https://static.wikia.nocookie.net/logopedia/images/4/4f/TN_todo_noticias_logo.svg/",
    link1: "https://www.youtube.com/embed/HPiv1pzIPRc",
    link2: "",
    link3: "https://embed8.alandesk.life/cvatt.html?get=VG9kb05vdGljaWFz",
    link4: "https://blackface.world/dtvpl.html?id=1225", //"https://www.latele-envivo.com/Embed/tn/op2.php",
    category: cat.news,
  },
  {
    id: 7,
    name: "El Trece",
    img: "https://i0.wp.com/directostv.teleame.com/wp-content/uploads/2019/10/El-Trece-en-vivo-Online.png?resize=1068%2C601&ssl=1",
    link1: "https://www.eltrecetv.com.ar/vivo/",
    link2: "",
    link3: "https://blackface.world/dtvpl.html?id=1095",
    link4: "https://embed8.alandesk.life/cvatt.html?get=QXJ0ZWFySEQ",
    category: cat.news,
  },
  {
    id: 8,
    name: "LN+",
    img: "https://static.wikia.nocookie.net/logopedia/images/0/0e/LN_Mas.svg/",
    link1: "https://www.youtube.com/embed/4e8Iw3Frf1A",
    link2: "https://lnmas.lanacion.com.ar/",
    link3: "https://blackface.world/dtvpl.html?id=1154",
    link4: "https://embed8.alandesk.life/cvatt.html?get=TGFfTmFjaW9u",
    category: cat.news,
  },
  {
    id: 9,
    name: "América",
    img: "https://i1.wp.com/static.americadigital.com.ar/americatv/images/america-tv-junio.png",
    link1: "https://www.americatv.com.ar/vivo",
    link2: "",
    link3: "https://blackface.world/dtvpl.html?id=1010",
    link4: "https://embed8.alandesk.life/cvatt.html?get=QW1lcmljYVRW",
    category: cat.news,
  },
  {
    id: 10,
    name: "A24",
    img: "https://www.a24.com/assets/img/296/header-logo.svg",
    link1: "https://www.youtube.com/embed/QGpHLgRnrx4",
    link2: "https://www.a24.com/vivo",
    link3: "https://blackface.world/dtvpl.html?id=1009",
    link4: "https://embed8.alandesk.life/cvatt.html?get=QW1lcmljYTI0",
    category: cat.news,
  },
  {
    id: 11,
    name: "Canal 26",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Canal_26_logo_%282022%29.svg/441px-Canal_26_logo_%282022%29.svg.png",
    link1: "https://www.youtube.com/embed/XcoIpif-pcM",
    link2: "https://www.canal26.com/canal26-en-vivo",
    link3: "https://blackface.world/dtvpl.html?id=1031",
    link4: "https://embed8.alandesk.life/cvatt.html?get=MjZfVFZfSEQ",
    category: cat.news,
  },
  {
    id: 12,
    name: "El Nueve ",
    img: "https://www.elnueve.com.ar/_next/image?url=%2Flogo%2FlogotipoC9.png&w=640&q=75",
    link1: "https://www.elnueve.com.ar/en-vivo",
    link2: "",
    link3: "https://blackface.world/dtvpl.html?id=1032",
    link4: "https://embed8.alandesk.life/cvatt.html?get=Q2FuYWw5",
    category: cat.news,
  },
  {
    id: 13,
    name: "C5N",
    img: "https://www.c5n.com/css-custom/326/images/logo-c5n.svg",
    link1: "https://www.youtube.com/embed/wBWK9tV9hBM",
    link2: "https://www.c5n.com/vivo",
    link3: "https://blackface.world/dtvpl.html?id=1028",
    link4: "https://embed8.alandesk.life/cvatt.html?get=QzVO",
    category: cat.news,
  },
  {
    id: 14,
    name: "TV Pública",
    img: "https://www.tvpublica.com.ar/static/img/branding/isologo.svg",
    link1:
      "https://vmf.edge-apps.net/embed/live.php?streamname=c7live01-20034&autoplay=true",
    link2: "",
    link3: "https://blackface.world/dtvpl.html?id=1156",
    link4: "https://embed8.alandesk.life/cvatt.html?get=Q2FuYWw3",
    category: cat.news,
  },
  {
    id: 15,
    name: "Crónica HD",
    img: "https://static.wikia.nocookie.net/logopedia/images/c/cd/Cr%C3%B3nica_TV_2018.svg/",
    link1: "https://www.youtube.com/embed/InSydaLSSlw?autoplay=true",
    link2: "https://www.cronica.com.ar/cronica-en-vivo", //https://vmf.edge-apps.net/embed/live.php?streamname=cronicatv_video1-100044&autoplay=true",
    link3: "https://embed8.alandesk.life/cvatt.html?get=Q3JvbmljYVRW",
    category: cat.news,
  },
  {
    id: 16,
    name: "CNN",
    img: "https://static.wikia.nocookie.net/logopedia/images/5/51/Logotipo_de_CNN_en_Espa%C3%B1ol.svg/",
    link1:
      "https://nosequewea.tk/fl?get=LmN2YXR0di5jb20uYXIvbGl2ZS9jNmVkcy9DTk5fZW5fRXNwYW5vbC9TQV9MaXZlX2Rhc2hfZW5jL0NOTl9lbl9Fc3Bhbm9sLm1wZA==&key=MGIyMGVkOWRhMGU1NDU3YzlkZmQzYWUwYjYwOTI0OTE=&key2=OTg5OTdhNzAyMGMxOGNiMjgxNzRhMjQ5MDE0NzgzMGE=",
    link3: "",
    category: cat.news,
  },
  {
    id: 17,
    name: "STAR+",
    img: "https://logospng.org/download/star-plus/logo-star-plus-256.png",
    link1: "https://librefutboltv.com/star-plus/",
    link2: "",
    link3: "https://canales.online/star-plus/",
    link4: "https://jac-tv.com/tvseg/starplus.php",
    category: cat.sports,
  },
  {
    id: 18,
    name: "ESPN",
    img: "https://static.wikia.nocookie.net/logopedia/images/3/34/ESPN.svg/",
    link1: "https://blackface.world/dtvpl.html?id=1104",
    link2: "",
    link3: "https://embed8.alandesk.life/cvatt.html?get=RVNQTjJIRA&lang=1",
    link4: "https://futbolfullenvivo.nl/canales/espn/",
    category: cat.sports,
  },
  {
    id: 19,
    name: "ESPN 2",
    img: "https://static.wikia.nocookie.net/logopedia/images/d/d5/ESPN2.svg/",
    link1: "https://blackface.world/dtvpl.html?id=1099",
    link2: "",
    link3: "https://embed8.alandesk.life/cvatt.html?get=RVNQTjJfQXJn",
    link4: "https://futbolfullenvivo.nl/canales/espn2/",
    category: cat.sports,
  },
  {
    id: 20,
    name: "ESPN 3",
    img: "https://static.wikia.nocookie.net/logopedia/images/d/d2/ESPN_3.svg/",
    link1: "https://blackface.world/dtvpl.html?id=1103",
    link2: "",
    link3: "https://embed8.alandesk.life/cvatt.html?get=RVNQTjM",
    link4: "https://futbolfullenvivo.nl/canales/espn3/",
    category: cat.sports,
  },
  {
    id: 21,
    name: "ESPN 4",
    img: "https://static.wikia.nocookie.net/logopedia/images/3/30/ESPN_4.svg/",
    link1: "https://futbolfullenvivo.nl/canales/espn4/",
    link2: "",
    link3: "https://futbolfullenvivo.nl/canales/espn4/op2.php",
    category: cat.sports,
  },
  {
    id: 22,
    name: "ESPN EXTRA",
    img: "https://static.wikia.nocookie.net/logopedia/images/b/b5/ESPN_Extra_Brazil_logo.png/",
    link1: "https://blackface.world/dtvpl.html?id=1107",
    link2: "",
    link3: "https://embed8.alandesk.life/cvatt.html?get=RVNQTkhE",
    link4: "https://futbolfullenvivo.nl/canales/espnextra/",
    category: cat.sports,
  },
  {
    id: 23,
    name: "ESPN PREMIUM",
    img: "https://static.wikia.nocookie.net/logopedia/images/5/5b/ESPN_Premium_%282022%29.svg/",
    link1: "https://blackface.world/dtvpl.html?id=1125&lang=1",
    link2: "",
    link3:
      "https://embed8.alandesk.life/cvatt.html?get=Rm94X1Nwb3J0c19QcmVtaXVuX0hE&lang=1",
    link4: "https://futbolfullenvivo.nl/canales/espn-premium/",
    category: cat.sports,
  },
  {
    id: 24,
    name: "TNT SPORTS",
    img: "https://static.wikia.nocookie.net/logopedia/images/9/9c/TNT_Sports.svg/",
    link1: "https://blackface.world/dtvpl.html?id=1233",
    link2: "",
    link3: "https://embed8.alandesk.life/cvatt.html?get=VE5UX1Nwb3J0c19IRA",
    link4: "https://futbolfullenvivo.nl/canales/tnt-sports/",
    category: cat,
  },
  {
    id: 25,
    name: "TyC Sports",
    img: "https://static.wikia.nocookie.net/logopedia/images/5/5d/TyC_Sports.svg/",
    link1: "https://blackface.world/dtvpl.html?id=1240",
    link2: "",
    link3: "https://embed8.alandesk.life/cvatt.html?get=VHlDU3BvcnQ",
    link4: "https://futbolfullenvivo.nl/canales/tyc/",
    category: cat.sports,
  },
  {
    id: 26,
    name: "FOX SPORTS",
    img: "https://static.wikia.nocookie.net/logopedia/images/b/b2/Fox_Sports_Argentina_2023.svg/",
    link1: "https://blackface.world/dtvpl.html?id=1118",
    link2: "",
    link3: "https://embed8.alandesk.life/cvatt.html?get=Rm94U3BvcnRz",
    link4: "https://futbolfullenvivo.nl/canales/fox-sports/",
    category: cat.sports,
  },
  {
    id: 27,
    name: "FOX SPORTS 2",
    img: "https://static.wikia.nocookie.net/logopedia/images/2/26/Fox_Sports_2_%28Argentina%29_2023.png/",
    link1: "https://embed8.alandesk.life/cvatt.html?get=Rm94U3BvcnRzMkhE",
    link2: "",
    link3: "https://embed47.thaidomains.co.in/cvatt.html?get=Rm94U3BvcnRzMkhE", //"https://my7mv.deportelibre.live/player?channelId=8a782cdd-35e7-4a57-b687-893a6d5a4f4e",
    category: cat.sports,
  },
  {
    id: 28,
    name: "FOX SPORTS 3",
    img: "https://static.wikia.nocookie.net/logopedia/images/8/83/Fox_Sports_3_%28Argentina%29_2023.png/",
    link1: "https://embed8.alandesk.life/cvatt.html?get=Rm94U3BvcnRzM0hE",
    link2: "",
    link3: "https://embed47.thaidomains.co.in/cvatt.html?get=Rm94U3BvcnRzM0hE",
    link4: "",
    category: cat.sports,
  },
  {
    id: 29,
    name: "DSPORTS",
    img: "https://static.wikia.nocookie.net/logopedia/images/5/5a/DSports.png/",
    link1: "https://blackface.world/dtvpl.html?id=1057",
    link2: "",
    link3: "https://bestformula.one/dtvpl2.html?id=1057&lang=1",
    link4: "",
    category: cat.sports,
  },
  {
    id: 30,
    name: "DSPORTS 2",
    img: "https://static.wikia.nocookie.net/logopedia/images/8/83/DSports2.png/",
    link1: "https://blackface.world/dtvpl.html?id=1063",
    link2: "",
    link3: "https://futbolfullenvivo.nl/canales/directv-sports2/",
    link4: "https:///bestformula.one/dtvpl2.html?id=1063&lang=1",
    category: cat.sports,
  },
  {
    id: 31,
    name: "DSPORTS+",
    img: "https://static.wikia.nocookie.net/logopedia/images/4/45/DSportsM%C3%A1s.png/",
    link1: "https://blackface.world/dtvpl.html?id=1071",
    link2: "",
    link3: "https://futbolfullenvivo.nl/canales/directv-sports-plus/",
    link4: "https://bestformula.one/dtvpl2.html?id=1071",
    category: cat.sports,
  },
  {
    id: 32,
    name: "HISTORY",
    img: "https://static.wikia.nocookie.net/logopedia/images/e/e8/History_2021.png/",
    link1: "https://blackface.world/dtvpl.html?id=1148",
    link2: "",
    link3: "https://www.latele-envivo.com/Embed/history/",
    link4: "https://www.latele-envivo.com/Embed/history/op2.php",
    category: cat.documental,
  },
  {
    id: 33,
    name: "HISTORY 2",
    img: "https://static.wikia.nocookie.net/logopedia/images/3/3a/History_2_%282022%29.png/",
    link1: "https://blackface.world/dtvpl.html?id=1147",
    link2: "",
    link3: "https://www.latele-envivo.com/Embed/history2/",
    link4: "https://www.latele-envivo.com/Embed/history2/op2.php",
    category: cat.documental,
  },
  {
    id: 34,
    name: "NATIONAL GEOGRAPHIC",
    img: "https://static.wikia.nocookie.net/logopedia/images/c/c6/National_Geographic_2008.svg/",
    link1: "https://blackface.world/dtvpl.html?id=1169",
    link2: "",
    link3: "https://www.latele-envivo.com/Embed/national-geographic/",
    link4: "https://embed8.alandesk.life/cvatt.html?get=TmF0R2VvSEQ=",
    category: cat.documental,
  },
  {
    id: 35,
    name: "Discovery",
    img: "https://static.wikia.nocookie.net/logopedia/images/4/40/Discovery%2C_Inc_logo.svg/",
    link1:
      "https://nosequewea.tk/dtvc?get=Ly9kdHZvdHQtY2JjLmFrYW1haXplZC5uZXQvZGFzaF9saXZlXzEwNzMvbWFuaWZlc3QubXBk&key=ODJmN2FhYWU0OWU1NTZjMTk4NWRhMDQ2MjMzN2RmNDM=&key2=NzZiMTNmZDhhMjk4ZDE4OGFjNTI1MjM4N2IyMjg2ODc=",
    link2: "https://megatelevisiontv.live/en-vivo/discovery/",
    link3:
      "https://nosequewea.tk/fl?get=LmN2YXR0di5jb20uYXIvbGl2ZS9jM2Vkcy9EaXNjb3ZlcnlIRC9TQV9MaXZlX2Rhc2hfZW5jXzJBL0Rpc2NvdmVyeUhELm1wZA==&key=YzI4M2M4NGE3YWYwZDdjOGI5YjYxMmE4ZmIyMmEwMDE=&key2=ZjQ1NTEwYzcyMWVlYmQ2ZWFhODZhMmUxNmNjYmQ3N2Q=",
    link4: "",
    category: cat.documental,
  },
  {
    id: 36,
    name: "Discovery Home & Health",
    img: "https://static.wikia.nocookie.net/logopedia/images/f/f3/Discovery_HnH_2022.svg/",
    link1: "https://blackface.world/dtvpl.html?id=1074",
    link2: "",
    link3: "https://www.latele-envivo.com/Embed/discovery-hh/",
    link4: "",
    category: cat.documental,
  },
  {
    id: 37,
    name: "Discovery ID",
    img: "https://static.wikia.nocookie.net/logopedia/images/5/58/CanalDiscoveryIDLA.png/",
    link1: "https://blackface.world/dtvpl.html?id=1076",
    link2: "",
    link3: "https://www.latele-envivo.com/Embed/discovery-investigacion/",
    link4: "",
    category: cat.documental,
  },
  {
    id: 38,
    name: "Discovery Science",
    img: "https://static.wikia.nocookie.net/logopedia/images/1/11/Discovery_Science_LA_2012.png/",
    link1:
      "https://nosequewea.tk/fl?get=LmN2YXR0di5jb20uYXIvbGl2ZS9jNmVkcy9EaXNjb3ZlcnlfU2NpZW5jZS9TQV9MaXZlX2Rhc2hfZW5jXzJBL0Rpc2NvdmVyeV9TY2llbmNlLm1wZA==&key=NDZiYTQwOWZiMDRlNDBmYjg2YjQ2NmQ5N2UzYTk1ODg=&key2=ZjEyOWZiOWI1ZDIxM2UyMGUyYWJlNTI5YjhjZjI1OTc=",
    link2: "",
    link3: "",
    link4: "",
    category: cat.documental,
  },
  {
    id: 39,
    name: "Discovery turbo",
    img: "https://static.wikia.nocookie.net/logopedia/images/a/ab/Discovery_Turbo_LatinAmerica_2021.svg/",
    link1: "https://blackface.world/dtvpl.html?id=1081",
    link2: "",
    link3: "https://www.latele-envivo.com/Embed/discovery-turbo/",
    link4: "",
    category: cat.documental,
  },
  {
    id: 40,
    name: "HGTV",
    img: "https://static.wikia.nocookie.net/logopedia/images/a/a8/HGTV_2010.svg/",
    link1: "https://blackface.world/dtvpl.html?id=1144",
    link2: "",
    link3: "https://www.latele-envivo.com/Embed/discovery-hgtv/",
    link4: "https://www.latele-envivo.com/Embed/discovery-hgtv/op2.php",
    category: cat.documental,
  },
  {
    id: 41,
    name: "MAS CHiC",
    img: "https://static.wikia.nocookie.net/logopedia/images/e/e9/M%C3%A1s_Chic.svg/",
    link1: "https://blackface.world/dtvpl.html?id=1161",
    link2: "",
    link3: "https://embed8.alandesk.life/cvatt.html?get=TWFzX0NoaWM=",
    link4: "https://www.latele-envivo.com/Embed/mas-chic/op2.php",
    category: cat.documental,
  },
  {
    id: 42,
    name: "DW",
    img: "https://static.wikia.nocookie.net/logopedia/images/7/75/Deutsche_Welle_symbol_2012.svg/",
    link1: "https://www.youtube.com/embed/tsStUN73_6I",
    link2: "",
    link3:
      "https://canales.online/m3u8.html?get=aHR0cHM6Ly9kd2FtZHN0cmVhbTEwNC5ha2FtYWl6ZWQubmV0L2hscy9saXZlLzIwMTU1MzAvZHdzdHJlYW0xMDQvaW5kZXgubTN1OA==",
    link4: "",
    category: cat.documental,
  },
  {
    id: 43,
    name: "TRU TV",
    img: "https://static.wikia.nocookie.net/logopedia/images/7/7d/TruTV_%282014%29_%28Purple%29.svg/",
    link1: "https://crytonep.github.io/mtonline/trutv.html",
    link2: "",
    link3: "https://telegratis.online/canal/trutv-en-vivo/",
    link4: "",
    category: cat.documental,
  },
  {
    id: 44,
    name: "SUN",
    img: "https://static.wikia.nocookie.net/logopedia/images/d/de/Sun_Channel_%282022%29.png/",
    link1: "https://megatelevisiontv.live/en-vivo/sun-channel/",
    link2: "",
    link3: "https://canales.online/en-vivo/sun-channel/",
    link4: "",
    category: cat.documental,
  },
  {
    id: 45,
    name: "Food Network",
    img: "https://static.wikia.nocookie.net/logopedia/images/5/59/FoodNetLogo.svg/",
    link1: "https://blackface.world/dtvpl.html?id=1113",
    link2: "",
    link3: "https://embed8.alandesk.life/cvatt.html?get=Rm9vZF9OZXR3b3Jr",
    link4: "https://www.latele-envivo.com/Embed/food-network/",
    category: cat.documental,
  },
  {
    id: 46,
    name: "El Gourmet",
    img: "https://static.wikia.nocookie.net/logopedia/images/d/da/Elgourmet_23.svg/",
    link1: "https://blackface.world/dtvpl.html?id=1093",
    link2: "",
    link3: "https://embed8.alandesk.life/cvatt.html?get=R291cm1ldA==",
    link4:
      "https://nosequewea.tk/fl?get=LmN2YXR0di5jb20uYXIvbGl2ZS9jM2Vkcy9Hb3VybWV0L1NBX0xpdmVfZGFzaF9lbmMvR291cm1ldC5tcGQ=&key=OTNkODUzYWM0YzhlMjRjZjAyOTVmNmY5N2VlNTNiZDM=&key2=ZmE1ODE3ZmFiNGZiMDU0Y2NlYTFhYmI5ZjNkNzY3ZWQ=",
    category: cat.documental,
  },
  {
    id: 47,
    name: "Flow Music",
    img: "https://static.wikia.nocookie.net/logopedia/images/0/0b/Flow_2021.svg/",
    link1: "https://embed8.alandesk.life/cvatt.html?get=Rmxvd19NdXNpY19YUA==",
    link2: "",
    link3:
      "https://nosequewea.tk/fl?get=LmN2YXR0di5jb20uYXIvbGl2ZS9jN2Vkcy9GbG93X011c2ljX1hQL1NBX0xpdmVfZGFzaF9lbmNfMkEvRmxvd19NdXNpY19YUC5tcGQ=&key=YjJhYWU0NGE3NDE0NGJlOGIyMTE4ZTIwZDE0MTJiYWI=&key2=OGE3YWU5OTZkMTJkOGQ1ZDU2MzdkMTA0NGY4ZTA4Yjc=",
    link4: "https://embed8.alandesk.life/cvatt.html?get=Rmxvd19NdXNpY18x",
    category: cat.music,
  },
  {
    id: 48,
    name: "Vorterix",
    img: "https://canales.online/img/logo_canal/Vorterix.png",
    link1:
      "https://www.youtube.com/embed/live_stream?channel=UCvCTWHCbBC0b9UIeLeNs8ug",
    link3: "",
    link4: "",
    category: cat.music,
  },
  {
    id: 49,
    name: "LUZZU TV",
    img: "http://luzutv.com.ar/wp-content/uploads/2021/07/LOGO-PNG-e1627149585606-300x87.png",
    link1: "http://luzutv.com.ar/",
    link2: "",
    link3:
      "https://player.twitch.tv/?channel=luzu_tv&parent=marco5x.github.io/marcTV",
    link4:
      "https://player.twitch.tv/video=601665123&parent=marco5x.github.io/marcTV",
    category: cat.music,
  },
  {
    id: 50,
    name: "La 100 HD",
    img: "https://static.wikia.nocookie.net/logopedia/images/3/3a/La_100_fm.png/",
    link1: "https://la100.cienradios.com/hd/",
    link2: "https://www.youtube.com/embed/icUYYWwb7qg",
    link3: "",
    category: cat.music,
  },

  {
    id: 51,
    name: "Radio Mitre",
    img: "https://4dproducciones.com.ar/wp-content/uploads/2020/10/Mitre.png",
    link1: "https://radiomitre.cienradios.com/hd/",
    link2: "https://www.youtube.com/embed/fsd92RSrtLA",
    link3: "",
    link4: "",
    category: cat.music,
  },
  {
    id: 52,
    name: "TCM",
    img: "https://static.wikia.nocookie.net/logopedia/images/d/df/TCM_%28Latin_America%29.svg/",
    link1: "https://www.latele-envivo.com/Embed/tcm/op2.php",
    link3: "https://crytonep.github.io/mtonline/tcm.html",
    link4: "",
    category: cat.movie,
  },
  {
    id: 53,
    name: "HBO",
    img: "https://static.wikia.nocookie.net/logopedia/images/c/c1/HBO.svg/",
    link1:
      "https://nosequewea.tk/dtvc?get=Ly9kdHZvdHQtYWJjLmFrYW1haXplZC5uZXQvZGFzaF9saXZlXzExNDAvbWFuaWZlc3QubXBk&key=OTllZWZjMDY4ZGIzNTA5YjlmMGNmNWIzNDExNDIxOWQ=&key2=NmMyM2UzMWE0ZDgzYjU2OGU4NGFlYzYwOWE2M2ViYzk=",
    link2: "https://www.latele-envivo.com/Embed/hbo/",
    link3: "https://www.latele-envivo.com/Embed/hbo/op2.php",
    link4:
      "https://nosequewea.tk/dtvc?get=Ly9kdHZvdHQtYWJjLmFrYW1haXplZC5uZXQvZGFzaF9saXZlXzExNDAvbWFuaWZlc3QubXBk&key=OTllZWZjMDY4ZGIzNTA5YjlmMGNmNWIzNDExNDIxOWQ=&key2=NmMyM2UzMWE0ZDgzYjU2OGU4NGFlYzYwOWE2M2ViYzk=",
    category: cat.movie,
  },
  {
    id: 54,
    name: "HBO 2",
    img: "https://static.wikia.nocookie.net/logopedia/images/9/95/HBO_2_2014.svg/",
    link1: "https://telefullenvivo.com/canales/hbo2/",
    link2: "",
    link3: "https://telefullenvivo.com/canales/hbo2/op2.php",
    link4: "",
    category: cat.movie,
  },
  {
    id: 55,
    name: "HBO+",
    img: "https://static.wikia.nocookie.net/logopedia/images/f/f9/Logohboplus2019.svg/",
    link1:
      "https://nosequewea.tk/dtvc?get=aHR0cHM6Ly9kdHZvdHQtYWJjLmFrYW1haXplZC5uZXQvZGFzaF9saXZlXzExNDEvbWFuaWZlc3QubXBk&key=Njc5NWEzMDNhOWU4NTE3ZmJjYTM4Mzc2YzBhZjJmNzY=&key2=MWJkYjMxNzIyOTA2NmFkMmQ3NGM0ODE0YTEzOGUxMzY=",
    link2:
      "https://nosequewea.tk/fl?get=LmN2YXR0di5jb20uYXIvbGl2ZS9jNmVkcy9IQk9fUGx1cy9TQV9MaXZlX2Rhc2hfZW5jL0hCT19QbHVzLm1wZA==&key=ZjBlN2Y3ZDQ1ODk5MGVkZmFiN2I5OGI0MTI1NjQ2MTU=&key2=NzkyMDU3NTRiN2Y4NGE2MjY2MWMyZGJlOWRlNWRkNWQ=",
    link3: "https://ok.ru/videoembed/6695123295815",
    link4:
      "https://player.twitch.tv/?channel=dt_yy83&parent=hdxchannel.xyz&parent=www.hdxchannel.xyz&parent=www.supertelevisionhd.com&parent=www.supertelevisionhd.net",
    category: cat.movie,
  },
  {
    id: 56,
    name: "HBO EXTREME",
    img: "https://static.wikia.nocookie.net/logopedia/images/b/b3/HBO_Xtreme_%282020%29.svg/",
    link1:
      "https://nosequewea.tk/fl?get=LmN2YXR0di5jb20uYXIvbGl2ZS9jNmVkcy9IQk9fRXh0cmVtZS9TQV9MaXZlX2Rhc2hfZW5jL0hC%20T19FeHRyZW1lLm1wZA==&key=ZDUwNDAxMWJiZWY0NjdjMGRlM2E3NTM0ZTMwMmE2ZDQ=&key2=MzM0MTAzZTJhYmUxNmZhYTdmOWFiMmUzMDk3YzVhNTg=",
    link3: "https://www.latele-envivo.com/Embed/hbo-xtreme/",
    category: cat.movie,
  },
  {
    id: 57,
    name: "SONY",
    img: "https://static.wikia.nocookie.net/logopedia/images/6/61/Sony_Channel_2019.svg/",
    link1:
      "https://nosequewea.tk/dtvc?get=Ly9kdHZvdHQtY2JjLmFrYW1haXplZC5uZXQvZGFzaF9saXZlXzExOTAvbWFuaWZlc3QubXBk&key=MTAxMGI5OWZiMTI0NTQwYWFhNDc1YTQxMjU5NzUxZWI=&key2=MTk3NWM2YmNjOTU2NmE2ZTk0YWIyNjNkYzhmMDRiNTc=",
    link3: "https://blackface.world/dtvpl.html?id=1190",
    link4: "https://www.latele-envivo.com/Embed/sony/",
    category: cat.movie,
  },
  {
    id: 58,
    name: "SONY MOVIES",
    img: "https://static.wikia.nocookie.net/logopedia/images/1/11/Sony_Movies_2019.svg/",
    link1:
      "https://nosequewea.tk/dtvc?get=Ly9kdHZvdHQtYWJjLmFrYW1haXplZC5uZXQvZGFzaF9saXZlXzEyNjMvbWFuaWZlc3QubXBk&key=MzkxYzEzNzAzNGYwNTM5MzhlZGJmMjY3OTk1NDlkZGM=&key2=MTlkNjQzZDhhNTBiMmY4MjljOTZhODk3ZjdkZjI1NWQ=",
    link3: "https://megatelevisiontv.live/en-vivo/sony-movies/",
    link4: "",
    category: cat.movie,
  },
  {
    id: 59,
    name: "Warner TV",
    img: "https://static.wikia.nocookie.net/logopedia/images/5/5e/Warner2018LA.png/",
    link1:
      "https://nosequewea.tk/dtvc?get=aHR0cHM6Ly9kdHZvdHQtY2JjLmFrYW1haXplZC5uZXQvZGFzaF9saXZlXzEyNDgvbWFuaWZlc3QubXBk&key=NTZhMjQ3MzJjN2M1NThhMGIyNDRkYzlkNWY5MTBmODc=&key2=NjFkZmVmODFjZWUxMWNiNDE5YTYxMjAyNzBiOTU4N2I=",
    link3: "https://blackface.world/dtvpl.html?id=1248",
    link4:
      "https://nosequewea.tk/fl?get=LmN2YXR0di5jb20uYXIvbGl2ZS9jN2Vkcy9XYXJuZXJIRC9TQV9MaXZlX2Rhc2hfZW5jXzJBL1dhcm5lckhELm1wZA==&key=MDY5YmQzZjBiNmMyNzk0NjdlMDg1NDlmMTdiZjViZDA=&key2=NWFmYTdlMzY5YTZkZTEwOTM4MThhODVhZjkxMmE3NzU=",
    category: cat.movie,
  },
  {
    id: 60,
    name: "UNIVERSAL PREMIERE",
    img: "https://static.wikia.nocookie.net/logopedia/images/3/3b/Universal_Premiere.svg/",
    link1:
      "https://nosequewea.tk/dtvc?get=aHR0cHM6Ly9kdHZvdHQtYWJjLmFrYW1haXplZC5uZXQvZGFzaF9saXZlXzEyNTYvbWFuaWZlc3QubXBk&key=ZDA4MGJlMjhhMGZjNTk3MGJmMWRlODk3ZjgwZDQwYmQ=&key2=YWI4MTg3ZDUwZDMxMWQzMGJjMGQ3ZGM2ZWI1Njk3ZDE=",
    link3: "https://www.latele-envivo.com/Embed/universal-premiere/",
    link4: "https://megatelevisiontv.live/en-vivo/universal-premiere/",
    category: cat.movie,
  },
  {
    id: 61,
    name: "UNIVERSAL CINEMA",
    img: "https://static.wikia.nocookie.net/logopedia/images/4/40/Universal_Cinema.svg/",
    link1: "https://www.latele-envivo.com/Embed/universal-cinema/",
    link3:
      "https://nosequewea.tk/dtvc?get=aHR0cHM6Ly9kdHZvdHQtYWJjLmFrYW1haXplZC5uZXQvZGFzaF9saXZlXzEyNTMvbWFuaWZlc3QubXBk&key=Y2UwYTdjODgzZTJhNTQzMGJiYTk3YTNkNjhlMGRhZjg=&key2=ZTMwZGQ0OTA4ZTY2NzYzNzM2OWRmYjY1ODJmNTRkNjQ=",
    link4: "https://www.latele-envivo.com/Embed/universal-cinema/",
    category: cat.movie,
  },
  {
    id: "adultos/62",
    name: "ADULTOS",
    img: "https://static.wikia.nocookie.net/logopedia/images/8/8c/PEGI_Sex.svg/",
    link1: "",
    category: cat.adults,
  },
];

export const datosPrivtes = [
  {
    id: 62,
    name: "Playboy TV",
    img: "https://static.wikia.nocookie.net/logopedia/images/3/37/Playboy_TV_Logo.svg/",
    link1: "https://embed8.alandesk.life/cvatt.html?get=UGxheWJveQ",
    link2: "https://www.latele-envivo.com/Embed/playboy/",
    category: cat.adults,
  },
  {
    id: 63,
    name: "Venus",
    img: "https://static.wikia.nocookie.net/logopedia/images/c/cc/Venus_2014.svg/",
    link1: "https://embed8.alandesk.life/cvatt.html?get=VmVudXM=",
    link2:
      "https://canales.online/m3u8.html?get=aHR0cHM6Ly9jZG5jZW50dXJ5LXZlbnVzaGQuem9sZWNoYW1lZGlhLm5ldC9wbGF5bGlzdC5tM3U4",
    category: cat.adults,
  },
  {
    id: 64,
    name: "SeXtreme",
    img: "https://static.wikia.nocookie.net/logopedia/images/2/23/Sextreme.png/",
    link1: "https://latele-envivo.com/Embed/sextreme/op2.php",
    link2: "https://www.latele-envivo.com/Embed/sextreme/op2.php",
    category: cat.adults,
  },
  {
    id: 65,
    name: "Hustler HD",
    img: "https://static.wikia.nocookie.net/logopedia/images/1/12/Hustler_HD.png/",
    link1: "https://www.latele-envivo.com/Embed/hustler/",
    link2: "https://megatelevisiontv.live/en-vivo/hustler/",
    category: cat.adults,
  },
  {
    id: 66,
    name: "Brazzers",
    img: "https://static.wikia.nocookie.net/logopedia/images/3/32/Brazzers_TV_1.svg/",
    link1: "https://www.latele-envivo.com/Embed/brazzers/",
    category: cat.adults,
  },
  {
    id: 67,
    name: "SEXY HOT",
    img: "http://login.sexyhot.com.br.s3-website-us-east-1.amazonaws.com/static/images/logo.png",
    link1: "https://www.latele-envivo.com/Embed/hot/",
    link2: "https://megatelevisiontv.live/en-vivo/sexyhot/",
    category: cat.adults,
  },
  {
    id: 68,
    name: "Tushy Teens",
    img: "https://static.wixstatic.com/media/dc5d85_369bb4a9a7c8409db0285b8436778077~mv2_d_3000_1319_s_2.png/v1/fill/w_894,h_393,al_c,usm_0.66_1.00_0.01/Teenager%20LOGO%20New%20Transparent.png",
    link1: "https://www.latele-envivo.com/Embed/teens/",
    category: cat.adults,
  },
  {
    id: 69,
    name: "DORCEL",
    img: "https://static.wikia.nocookie.net/logopedia/images/b/be/Dorcel_TV_2022.svg/",
    link1: "https://www.latele-envivo.com/Embed/dorcel/",
    category: cat.adults,
  },
  {
    id: 70,
    name: "Dream Sex",
    img: "https://static.wikia.nocookie.net/logopedia/images/0/09/XXXTentacion_2018.svg/",
    link1: "https://www.latele-envivo.com/Embed/dreamsex/",
    category: cat.adults,
  },
  {
    id: 71,
    name: "Private",
    img: "https://static.wikia.nocookie.net/logopedia/images/9/98/PRIVATE_TV.png/",
    link1: "https://megatelevisiontv.live/en-vivo/private/",
    link2: "#",
    category: cat.adults,
  },
];

//https://www.latele-envivo.com/
//https://sfntv.xyz/inicio
//https://megatelevisiontv.live/
//https://canales.online/
